In [103]:
from copy import deepcopy
import hashlib
import json
from pathlib import Path

import mlflow
import numpy as np
import polars as pl
import torch
import torch.nn as nn
import torch.nn.functional as F
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
from rdkit.Chem.Scaffolds import MurckoScaffold
from sklearn.metrics import r2_score
from torch.utils.data import DataLoader, TensorDataset
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader as GeoDataLoader
from torch_geometric.nn import BatchNorm, GINEConv, global_add_pool, global_mean_pool

pl.Config.set_tbl_cols(-1)       # Wyświetl wszystkie kolumny
pl.Config.set_tbl_rows(20)       # Ustaw limit wierszy (lub -1 dla wszystkich)
pl.Config.set_fmt_str_lengths(100) # Nie skracaj długich ciągów (np. SMILES)

polars.config.Config

In [104]:
df = pl.read_parquet("processed_data/ChEMBL_processed.parquet")

In [105]:
print(df.columns)

['activity_id', 'molregno', 'canonical_smiles', 'mw_freebase', 'alogp', 'hba', 'hbd', 'psa', 'rtb', 'aromatic_rings', 'qed_weighted', 'standard_value', 'standard_units', 'standard_type', 'standard_relation', 'pchembl_value', 'target_chembl_id', 'target_name', 'confidence_score', 'pIC50']

In [106]:
radius = 2
n_bits = 2048
mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=radius, fpSize=n_bits)

def get_scaffold_smiles(smiles: str) -> str | None:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return MurckoScaffold.MurckoScaffoldSmiles(mol=mol, includeChirality=False)

def fp_from_smiles(smiles: str) -> np.ndarray | None:
    """Zwraca fingerprint Morgana albo None dla niepoprawnego SMILES."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    try:
        return mfpgen.GetFingerprintAsNumPy(mol).astype(np.float32)
    except Exception:
        return None

class MLPBaseline(nn.Module):
    def __init__(self, input_size=2048):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_size, 512),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, 1),
        )
        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        return self.network(x)

class GNNRegressor(torch.nn.Module):
    def __init__(self, node_features: int, edge_features: int, hidden_dim: int = 128, num_layers: int = 4, dropout: float = 0.15, pooling: str = 'mean'):
        super().__init__()
        if pooling not in {'mean', 'add'}:
            raise ValueError("pooling must be 'mean' or 'add'")

        self.pooling = pooling
        self.dropout = dropout
        self.node_proj = nn.Linear(node_features, hidden_dim)
        self.edge_encoder = nn.Sequential(
            nn.Linear(edge_features, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
        )

        self.convs = nn.ModuleList()
        self.norms = nn.ModuleList()
        for _ in range(num_layers):
            mlp = nn.Sequential(
                nn.Linear(hidden_dim, hidden_dim),
                nn.ReLU(),
                nn.Linear(hidden_dim, hidden_dim),
            )
            self.convs.append(GINEConv(mlp, edge_dim=hidden_dim))
            self.norms.append(BatchNorm(hidden_dim))

        self.head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim // 2, 1),
        )

    def _pool(self, x, batch):
        if self.pooling == 'add':
            return global_add_pool(x, batch)
        return global_mean_pool(x, batch)

    def forward(self, data):
        x, edge_index, edge_attr, batch = data.x, data.edge_index, data.edge_attr, data.batch
        x = self.node_proj(x)
        edge_attr = self.edge_encoder(edge_attr)

        for conv, norm in zip(self.convs, self.norms):
            residual = x
            x = conv(x, edge_index, edge_attr)
            x = norm(x)
            x = F.relu(x)
            x = F.dropout(x, p=self.dropout, training=self.training)
            x = x + residual

        x = self._pool(x, batch)
        return self.head(x)

In [107]:
## Uczenie
import os
import random


def seed_everything(seed: int = 42, deterministic: bool = False):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = deterministic
    torch.backends.cudnn.benchmark = not deterministic


def get_device(prefer_cuda: bool = True):
    if prefer_cuda and torch.cuda.is_available():
        return torch.device('cuda')
    return torch.device('cpu')


def compute_num_workers(max_workers: int = 8):
    cpu_count = os.cpu_count() or 1
    return max(0, min(max_workers, cpu_count // 2))


torch.set_float32_matmul_precision('high')

device = get_device(prefer_cuda=True)
seed_everything(42, deterministic=False)
print(f'Using device: {device}')
if device.type == 'cuda':
    print(f'GPU: {torch.cuda.get_device_name(0)}')

Using device: cuda
GPU: NVIDIA GeForce RTX 4060 Ti

In [108]:
def _forward_batch(model, batch, device, is_gnn=False):
    if is_gnn:
        batch = batch.to(device, non_blocking=True)
        target = batch.y.view(-1, 1)
        out = model(batch)
    else:
        x, y = batch
        x = x.to(device, non_blocking=True)
        target = y.to(device, non_blocking=True).view(-1, 1)
        out = model(x)
    return out, target


def train_one_epoch(model, loader, optimizer, criterion, device, is_gnn=False, clip_grad=1.0, scaler=None, use_amp=False):
    model.train()
    total_loss = 0.0

    for batch in loader:
        optimizer.zero_grad(set_to_none=True)
        with torch.amp.autocast(device_type=device.type, enabled=use_amp):
            out, target = _forward_batch(model, batch, device, is_gnn=is_gnn)
            loss = criterion(out, target)

        if torch.isnan(loss):
            print('Loss exploded to NaN! Stopping...')
            return float('nan')

        if scaler is not None:
            scaler.scale(loss).backward()
            if clip_grad is not None:
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=clip_grad)
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            if clip_grad is not None:
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=clip_grad)
            optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)


def predict_arrays(model, loader, device, is_gnn=False, use_amp=False):
    model.eval()
    all_preds = []
    all_targets = []

    with torch.no_grad():
        for batch in loader:
            with torch.amp.autocast(device_type=device.type, enabled=use_amp):
                out, target = _forward_batch(model, batch, device, is_gnn=is_gnn)
            all_preds.append(out.cpu().numpy())
            all_targets.append(target.cpu().numpy())

    preds = np.concatenate(all_preds).ravel()
    targets = np.concatenate(all_targets).ravel()
    return targets, preds


def evaluate_loss(model, loader, criterion, device, is_gnn=False, use_amp=False):
    model.eval()
    total_loss = 0.0

    with torch.no_grad():
        for batch in loader:
            with torch.amp.autocast(device_type=device.type, enabled=use_amp):
                out, target = _forward_batch(model, batch, device, is_gnn=is_gnn)
                loss = criterion(out, target)
            total_loss += loss.item()

    return total_loss / len(loader)


def evaluate_r2(model, loader, device, is_gnn=False, use_amp=False):
    targets, preds = predict_arrays(model, loader, device, is_gnn=is_gnn, use_amp=use_amp)
    if np.isnan(preds).any():
        print(f'BLAD: Predykcje modelu zawieraja NaN! (Pierwsze 5: {preds[:5]})')
    if np.isnan(targets).any():
        print('BLAD: Etykiety zawieraja NaN!')
    return r2_score(targets, preds)

In [109]:
df_temp = df.with_columns(
    pl.col("canonical_smiles").map_elements(fp_from_smiles, return_dtype=pl.Object).alias("fp")
)
df_clean = df_temp.filter(
    (pl.col("fp").is_not_null()) & 
    (pl.col("pIC50").is_not_null()) &
    (pl.col("pIC50").is_not_nan())
)
print(f"Liczba próbek po pełnym oczyszczeniu: {len(df_clean)}")
print(f"Odrzucono {len(df) - len(df_clean)} błędnych cząsteczek.")

Liczba próbek po pełnym oczyszczeniu: 15723
Odrzucono 0 błędnych cząsteczek.

In [110]:
def random_split_df(df_fp: pl.DataFrame, test_size=0.1, val_size=0.1, seed=42):
    df_shuffled = df_fp.sample(fraction=1.0, seed=seed)
    n = len(df_shuffled)
    n_test = int(test_size * n)
    n_val = int(val_size * n)
    test_df = df_shuffled[:n_test]
    val_df = df_shuffled[n_test:n_test + n_val]
    train_df = df_shuffled[n_test + n_val:]
    return train_df, val_df, test_df


def scaffold_split(df_fp: pl.DataFrame, test_size=0.1, val_size=0.1, seed=42):
    df_scaff = df_fp.with_row_count('row_id').with_columns(
        pl.col('canonical_smiles').map_elements(get_scaffold_smiles, return_dtype=pl.Utf8).alias('scaffold')
    )
    df_scaff = df_scaff.filter(pl.col('scaffold').is_not_null())

    stats = (
        df_scaff.group_by('scaffold')
        .agg(pl.len().alias('count'))
        .sort('count', descending=True)
    )

    rng = np.random.default_rng(seed)
    scaffold_rows = stats.to_dicts()
    rng.shuffle(scaffold_rows)
    scaffold_rows.sort(key=lambda r: r['count'], reverse=True)

    total = int(df_scaff.height)
    target_test = int(total * test_size)
    target_val = int(total * val_size)

    split_counts = {'train': 0, 'val': 0, 'test': 0}
    scaff_to_split = {}

    for row in scaffold_rows:
        scaf = row['scaffold']
        count = int(row['count'])
        need_test = target_test - split_counts['test']
        need_val = target_val - split_counts['val']

        if need_test > 0 and (need_test >= need_val):
            split = 'test'
        elif need_val > 0:
            split = 'val'
        else:
            split = 'train'

        scaff_to_split[scaf] = split
        split_counts[split] += count

    df_labeled = df_scaff.with_columns(
        pl.col('scaffold').replace_strict(scaff_to_split, default='train').alias('split')
    )

    return (
        df_labeled.filter(pl.col('split') == 'train'),
        df_labeled.filter(pl.col('split') == 'val'),
        df_labeled.filter(pl.col('split') == 'test'),
    )


def get_split_dfs(df_fp: pl.DataFrame, split_type='random', seed=42):
    if split_type == 'scaffold':
        return scaffold_split(df_fp, seed=seed)
    if split_type == 'random':
        return random_split_df(df_fp, seed=seed)
    raise ValueError("split_type must be 'random' or 'scaffold'")


def build_mlp_loaders(df_fp: pl.DataFrame, split_type='random', batch_size=64, seed=42):
    train_df, val_df, test_df = get_split_dfs(df_fp, split_type=split_type, seed=seed)

    X_train = np.stack(train_df['fp'].to_list())
    y_train = train_df['pIC50'].to_numpy().astype(np.float32)
    X_val = np.stack(val_df['fp'].to_list())
    y_val = val_df['pIC50'].to_numpy().astype(np.float32)
    X_test = np.stack(test_df['fp'].to_list())
    y_test = test_df['pIC50'].to_numpy().astype(np.float32)

    num_workers = compute_num_workers()
    train_loader = DataLoader(
        TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train)),
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=(device.type == 'cuda'),
        persistent_workers=(num_workers > 0),
    )
    val_loader = DataLoader(
        TensorDataset(torch.from_numpy(X_val), torch.from_numpy(y_val)),
        batch_size=batch_size,
        num_workers=num_workers,
        pin_memory=(device.type == 'cuda'),
        persistent_workers=(num_workers > 0),
    )
    test_loader = DataLoader(
        TensorDataset(torch.from_numpy(X_test), torch.from_numpy(y_test)),
        batch_size=batch_size,
        num_workers=num_workers,
        pin_memory=(device.type == 'cuda'),
        persistent_workers=(num_workers > 0),
    )
    return train_loader, val_loader, test_loader

In [111]:
ATOMIC_NUM_LIST = [1, 5, 6, 7, 8, 9, 14, 15, 16, 17, 34, 35, 53]
HYBRIDIZATION_TYPES = [
    Chem.rdchem.HybridizationType.SP,
    Chem.rdchem.HybridizationType.SP2,
    Chem.rdchem.HybridizationType.SP3,
    Chem.rdchem.HybridizationType.SP3D,
    Chem.rdchem.HybridizationType.SP3D2,
]
BOND_TYPES = [
    Chem.rdchem.BondType.SINGLE,
    Chem.rdchem.BondType.DOUBLE,
    Chem.rdchem.BondType.TRIPLE,
    Chem.rdchem.BondType.AROMATIC,
]
BOND_STEREO_TYPES = [
    Chem.rdchem.BondStereo.STEREONONE,
    Chem.rdchem.BondStereo.STEREOZ,
    Chem.rdchem.BondStereo.STEREOE,
    Chem.rdchem.BondStereo.STEREOCIS,
    Chem.rdchem.BondStereo.STEREOTRANS,
]
CHIRAL_TAGS = [
    Chem.rdchem.ChiralType.CHI_UNSPECIFIED,
    Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW,
    Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW,
]

GRAPH_CACHE_DIR = Path('processed_data/graph_cache')
GRAPH_CACHE_DIR.mkdir(parents=True, exist_ok=True)
GRAPH_DATA_CACHE = GRAPH_CACHE_DIR / 'all_graphs.pt'
GRAPH_SPLIT_CACHE_TEMPLATE = 'split_{split}_seed{seed}.pt'


def one_hot_encode(value, categories):
    return [1 if value == cat else 0 for cat in categories]


def mol_to_graph(smiles: str, target: float):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    node_feats = []
    for atom in mol.GetAtoms():
        atomic_num = atom.GetAtomicNum()
        one_hot_atomic = one_hot_encode(atomic_num, ATOMIC_NUM_LIST) if atomic_num in ATOMIC_NUM_LIST else [0] * len(ATOMIC_NUM_LIST)

        hybridization = atom.GetHybridization()
        one_hot_hybrid = one_hot_encode(hybridization, HYBRIDIZATION_TYPES) if hybridization in HYBRIDIZATION_TYPES else [0] * len(HYBRIDIZATION_TYPES)

        chiral_tag = atom.GetChiralTag()
        one_hot_chiral = one_hot_encode(chiral_tag, CHIRAL_TAGS) if chiral_tag in CHIRAL_TAGS else [0] * len(CHIRAL_TAGS)

        degree = atom.GetTotalDegree() / 4.0
        formal_charge = (atom.GetFormalCharge() + 4) / 8.0
        num_hs = atom.GetTotalNumHs() / 4.0
        total_valence = atom.GetTotalValence() / 8.0
        num_radical = atom.GetNumRadicalElectrons() / 2.0
        is_aromatic = float(atom.GetIsAromatic())
        is_in_ring = float(atom.IsInRing())

        node_feats.append(
            one_hot_atomic
            + one_hot_hybrid
            + one_hot_chiral
            + [degree, formal_charge, num_hs, total_valence, num_radical, is_aromatic, is_in_ring]
        )

    x = torch.tensor(node_feats, dtype=torch.float)

    edge_index_list = []
    edge_attr_list = []
    for bond in mol.GetBonds():
        u = bond.GetBeginAtomIdx()
        v = bond.GetEndAtomIdx()

        bond_type = bond.GetBondType()
        one_hot_bond = one_hot_encode(bond_type, BOND_TYPES) if bond_type in BOND_TYPES else [0] * len(BOND_TYPES)

        stereo = bond.GetStereo()
        one_hot_stereo = one_hot_encode(stereo, BOND_STEREO_TYPES) if stereo in BOND_STEREO_TYPES else [0] * len(BOND_STEREO_TYPES)

        bond_feats = one_hot_bond + one_hot_stereo + [float(bond.GetIsConjugated()), float(bond.IsInRing())]
        edge_index_list.extend([[u, v], [v, u]])
        edge_attr_list.extend([bond_feats, bond_feats])

    edge_dim = len(BOND_TYPES) + len(BOND_STEREO_TYPES) + 2
    if edge_index_list:
        edge_index = torch.tensor(edge_index_list, dtype=torch.long).t().contiguous()
        edge_attr = torch.tensor(edge_attr_list, dtype=torch.float)
    else:
        edge_index = torch.empty((2, 0), dtype=torch.long)
        edge_attr = torch.empty((0, edge_dim), dtype=torch.float)

    return Data(x=x, edge_index=edge_index, edge_attr=edge_attr, y=torch.tensor([target], dtype=torch.float), smiles=smiles)


def _build_all_graphs(df_fp: pl.DataFrame):
    graphs = []
    smiles_to_idx = {}

    for row in df_fp.select(['canonical_smiles', 'pIC50']).iter_rows(named=True):
        smiles = row['canonical_smiles']
        if smiles in smiles_to_idx:
            continue
        g = mol_to_graph(smiles, float(row['pIC50']))
        if g is not None:
            smiles_to_idx[smiles] = len(graphs)
            graphs.append(g)

    return graphs, smiles_to_idx


def load_or_build_graph_cache(df_fp: pl.DataFrame):
    if GRAPH_DATA_CACHE.exists():
        try:
            cached = torch.load(GRAPH_DATA_CACHE, weights_only=False)
            return cached['graphs'], cached['smiles_to_idx']
        except Exception as exc:
            print(f'Cache load failed ({exc}); rebuilding graph cache...')

    graphs, smiles_to_idx = _build_all_graphs(df_fp)
    torch.save({'graphs': graphs, 'smiles_to_idx': smiles_to_idx}, GRAPH_DATA_CACHE)
    return graphs, smiles_to_idx


def _subset_graphs(df_part: pl.DataFrame, all_graphs, smiles_to_idx):
    graphs = []
    for smiles, target in df_part.select(['canonical_smiles', 'pIC50']).iter_rows():
        idx = smiles_to_idx.get(smiles)
        if idx is None:
            continue
        g = deepcopy(all_graphs[idx])
        g.y = torch.tensor([float(target)], dtype=torch.float)
        graphs.append(g)
    return graphs


def build_gnn_loaders(df_fp: pl.DataFrame, split_type='random', batch_size=64, seed=42):
    train_df, val_df, test_df = get_split_dfs(df_fp, split_type=split_type, seed=seed)

    all_graphs, smiles_to_idx = load_or_build_graph_cache(df_fp)

    train_graphs = _subset_graphs(train_df, all_graphs, smiles_to_idx)
    val_graphs = _subset_graphs(val_df, all_graphs, smiles_to_idx)
    test_graphs = _subset_graphs(test_df, all_graphs, smiles_to_idx)

    num_workers = compute_num_workers()
    train_loader = GeoDataLoader(
        train_graphs,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=(device.type == 'cuda'),
        persistent_workers=(num_workers > 0),
    )
    val_loader = GeoDataLoader(
        val_graphs,
        batch_size=batch_size,
        num_workers=num_workers,
        pin_memory=(device.type == 'cuda'),
        persistent_workers=(num_workers > 0),
    )
    test_loader = GeoDataLoader(
        test_graphs,
        batch_size=batch_size,
        num_workers=num_workers,
        pin_memory=(device.type == 'cuda'),
        persistent_workers=(num_workers > 0),
    )
    return train_loader, val_loader, test_loader

In [112]:
## Konfiguracja eksperymentow (uzywana przez komorki ponizej)
EPOCHS_DEFAULT = 100
LR_DEFAULT = 3e-4
BATCH_SIZE_DEFAULT = 64
SEED_DEFAULT = 42

EARLY_STOPPING_PATIENCE_DEFAULT = 12
MIN_DELTA_DEFAULT = 1e-4
WEIGHT_DECAY_DEFAULT = 1e-5
POOLING_DEFAULT = 'mean'

print(
    f'Domyslne parametry: epochs={EPOCHS_DEFAULT}, lr={LR_DEFAULT}, batch={BATCH_SIZE_DEFAULT}, '
    f'seed={SEED_DEFAULT}, patience={EARLY_STOPPING_PATIENCE_DEFAULT}, pooling={POOLING_DEFAULT}'
)

Domyslne parametry: epochs=100, lr=0.0003, batch=64, seed=42, patience=12, pooling=mean

In [113]:
fp_has_nan = any(np.isnan(fp).any() for fp in df_clean["fp"])
print(f"NaN w fingerprintach: {fp_has_nan}")

NaN w fingerprintach: False

In [114]:
# Narzedzia do pojedynczego treningu i kolekcji wynikow
results_table = []
MODEL_CACHE_DIR = Path('processed_data/model_cache')
MODEL_CACHE_DIR.mkdir(parents=True, exist_ok=True)


def _make_cache_key(config: dict) -> str:
    payload = json.dumps(config, sort_keys=True)
    return hashlib.sha256(payload.encode('utf-8')).hexdigest()[:16]


def get_model_cache_path(config: dict, namespace: str = 'default') -> Path:
    key = _make_cache_key(config)
    return MODEL_CACHE_DIR / f'{namespace}_{key}.pt'


def _upsert_result(result: dict, replace_existing: bool, model_type: str, split_type: str, seed: int, pooling: str, gnn_hidden_dim: int, gnn_num_layers: int, gnn_dropout: float, lr: float, weight_decay: float):
    if replace_existing:
        results_table[:] = [
            r
            for r in results_table
            if not (
                r['model'] == model_type
                and r['split'] == split_type
                and r.get('seed') == seed
                and r.get('pooling') == pooling
                and r.get('gnn_hidden_dim') == gnn_hidden_dim
                and r.get('gnn_num_layers') == gnn_num_layers
                and r.get('gnn_dropout') == gnn_dropout
                and r.get('lr') == lr
                and r.get('weight_decay') == weight_decay
            )
        ]
    results_table.append(result)


def train_and_score(
    model_type: str,
    split_type: str,
    epochs: int = EPOCHS_DEFAULT,
    lr: float = LR_DEFAULT,
    batch_size: int = BATCH_SIZE_DEFAULT,
    seed: int = SEED_DEFAULT,
    log_mlflow: bool = False,
    replace_existing: bool = True,
    evaluate_test: bool = False,
    early_stopping_patience: int = EARLY_STOPPING_PATIENCE_DEFAULT,
    min_delta: float = MIN_DELTA_DEFAULT,
    weight_decay: float = WEIGHT_DECAY_DEFAULT,
    pooling: str = POOLING_DEFAULT,
    gnn_hidden_dim: int = 128,
    gnn_num_layers: int = 4,
    gnn_dropout: float = 0.15,
    prefer_cuda: bool = True,
    deterministic: bool = False,
    use_amp: bool = True,
    use_model_cache: bool = True,
    force_retrain: bool = False,
    cache_namespace: str = 'default',
):
    """Trenuje model z early stopping i wyborem najlepszego checkpointu po val_loss."""
    seed_everything(seed, deterministic=deterministic)
    device = get_device(prefer_cuda=prefer_cuda)
    amp_enabled = bool(use_amp and device.type == 'cuda')
    scaler = torch.amp.GradScaler(device='cuda', enabled=amp_enabled)

    if model_type == 'MLP':
        train_loader, val_loader, test_loader = build_mlp_loaders(
            df_clean, split_type=split_type, batch_size=batch_size, seed=seed
        )
        model = MLPBaseline().to(device)
        is_gnn_flag = False
    elif model_type == 'GNN':
        train_loader, val_loader, test_loader = build_gnn_loaders(
            df_clean, split_type=split_type, batch_size=batch_size, seed=seed
        )
        sample_graph = train_loader.dataset[0]
        model = GNNRegressor(
            node_features=sample_graph.num_node_features,
            edge_features=sample_graph.edge_attr.shape[1],
            hidden_dim=gnn_hidden_dim,
            num_layers=gnn_num_layers,
            dropout=gnn_dropout,
            pooling=pooling,
        ).to(device)
        is_gnn_flag = True
    else:
        raise ValueError("model_type must be 'MLP' or 'GNN'")

    cache_config = {
        'model_type': model_type,
        'split_type': split_type,
        'seed': seed,
        'epochs': epochs,
        'lr': lr,
        'batch_size': batch_size,
        'early_stopping_patience': early_stopping_patience,
        'min_delta': min_delta,
        'weight_decay': weight_decay,
        'pooling': pooling,
        'gnn_hidden_dim': gnn_hidden_dim,
        'gnn_num_layers': gnn_num_layers,
        'gnn_dropout': gnn_dropout,
    }
    model_cache_path = get_model_cache_path(cache_config, namespace=cache_namespace)

    if use_model_cache and model_cache_path.exists() and not force_retrain:
        try:
            cached = torch.load(model_cache_path, map_location=device, weights_only=False)
            model.load_state_dict(cached['model_state_dict'])

            r2_val = evaluate_r2(model, val_loader, device, is_gnn=is_gnn_flag, use_amp=amp_enabled)
            r2_test = evaluate_r2(model, test_loader, device, is_gnn=is_gnn_flag, use_amp=amp_enabled) if evaluate_test else None

            result = cached.get('result', {}).copy()
            result.update({
                'model': model_type,
                'split': split_type,
                'seed': seed,
                'r2_val': r2_val,
                'r2_test': r2_test,
                'device': str(device),
                'amp_enabled': amp_enabled,
                'from_cache': True,
                'cache_path': str(model_cache_path),
            })

            _upsert_result(
                result=result,
                replace_existing=replace_existing,
                model_type=model_type,
                split_type=split_type,
                seed=seed,
                pooling=pooling,
                gnn_hidden_dim=gnn_hidden_dim,
                gnn_num_layers=gnn_num_layers,
                gnn_dropout=gnn_dropout,
                lr=lr,
                weight_decay=weight_decay,
            )
            print(f'Loaded cached model: {model_cache_path.name} | val R2={r2_val:.3f}')
            return result
        except Exception as exc:
            print(f'Model cache load failed ({exc}); training from scratch...')

    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode='min',
        factor=0.5,
        patience=max(2, early_stopping_patience // 3),
        min_lr=1e-6,
    )
    criterion = torch.nn.MSELoss()

    train_losses = []
    val_losses = []
    val_r2_history = []
    lr_history = []
    best_val_loss = float('inf')
    best_epoch = -1
    best_state = None
    no_improve_epochs = 0

    for epoch in range(epochs):
        epoch_train_loss = train_one_epoch(
            model,
            train_loader,
            optimizer,
            criterion,
            device,
            is_gnn=is_gnn_flag,
            clip_grad=1.0,
            scaler=scaler,
            use_amp=amp_enabled,
        )
        epoch_val_loss = evaluate_loss(model, val_loader, criterion, device, is_gnn=is_gnn_flag, use_amp=amp_enabled)
        epoch_val_r2 = evaluate_r2(model, val_loader, device, is_gnn=is_gnn_flag, use_amp=amp_enabled)
        current_lr = optimizer.param_groups[0]['lr']

        train_losses.append(epoch_train_loss)
        val_losses.append(epoch_val_loss)
        val_r2_history.append(epoch_val_r2)
        lr_history.append(current_lr)

        scheduler.step(epoch_val_loss)

        if epoch_val_loss < (best_val_loss - min_delta):
            best_val_loss = epoch_val_loss
            best_epoch = epoch + 1
            best_state = deepcopy(model.state_dict())
            no_improve_epochs = 0
        else:
            no_improve_epochs += 1

        if no_improve_epochs >= early_stopping_patience:
            break

    if best_state is not None:
        model.load_state_dict(best_state)

    avg_train_loss = float(np.mean(train_losses))
    avg_val_loss = float(np.mean(val_losses))

    r2_val = evaluate_r2(model, val_loader, device, is_gnn=is_gnn_flag, use_amp=amp_enabled)
    r2_test = evaluate_r2(model, test_loader, device, is_gnn=is_gnn_flag, use_amp=amp_enabled) if evaluate_test else None

    if log_mlflow:
        with mlflow.start_run(run_name=f'{model_type}_{split_type}'):
            mlflow.log_params({
                'model_type': model_type,
                'split_type': split_type,
                'epochs': epochs,
                'epochs_trained': len(train_losses),
                'best_epoch': best_epoch,
                'lr': lr,
                'batch_size': batch_size,
                'seed': seed,
                'evaluate_test': evaluate_test,
                'early_stopping_patience': early_stopping_patience,
                'min_delta': min_delta,
                'weight_decay': weight_decay,
                'pooling': pooling,
                'gnn_hidden_dim': gnn_hidden_dim,
                'gnn_num_layers': gnn_num_layers,
                'gnn_dropout': gnn_dropout,
                'device': str(device),
                'amp_enabled': amp_enabled,
                'deterministic': deterministic,
            })
            mlflow.log_metric('avg_train_loss', avg_train_loss)
            mlflow.log_metric('avg_val_loss', avg_val_loss)
            mlflow.log_metric('best_val_loss', best_val_loss)
            mlflow.log_metric('r2_val', r2_val)
            if r2_test is not None:
                mlflow.log_metric('r2_test', r2_test)
            for i, (tr, va, va_r2, lri) in enumerate(zip(train_losses, val_losses, val_r2_history, lr_history), start=1):
                mlflow.log_metric('train_loss_epoch', tr, step=i)
                mlflow.log_metric('val_loss_epoch', va, step=i)
                mlflow.log_metric('val_r2_epoch', va_r2, step=i)
                mlflow.log_metric('lr_epoch', lri, step=i)
            mlflow.pytorch.log_model(model, 'model')

    result = {
        'model': model_type,
        'split': split_type,
        'seed': seed,
        'epochs': epochs,
        'epochs_trained': len(train_losses),
        'best_epoch': best_epoch,
        'lr': lr,
        'batch_size': batch_size,
        'weight_decay': weight_decay,
        'pooling': pooling,
        'gnn_hidden_dim': gnn_hidden_dim,
        'gnn_num_layers': gnn_num_layers,
        'gnn_dropout': gnn_dropout,
        'avg_train_loss': avg_train_loss,
        'avg_val_loss': avg_val_loss,
        'best_val_loss': float(best_val_loss),
        'r2_val': r2_val,
        'r2_test': r2_test,
        'device': str(device),
        'amp_enabled': amp_enabled,
        'from_cache': False,
        'cache_path': str(model_cache_path),
    }

    if use_model_cache:
        try:
            torch.save({'model_state_dict': model.state_dict(), 'result': result}, model_cache_path)
        except Exception as exc:
            print(f'Warning: could not save model cache ({exc})')

    _upsert_result(
        result=result,
        replace_existing=replace_existing,
        model_type=model_type,
        split_type=split_type,
        seed=seed,
        pooling=pooling,
        gnn_hidden_dim=gnn_hidden_dim,
        gnn_num_layers=gnn_num_layers,
        gnn_dropout=gnn_dropout,
        lr=lr,
        weight_decay=weight_decay,
    )

    if r2_test is None:
        print(
            f"{model_type} | {split_type} | device={device}: avg train loss={avg_train_loss:.4f}, avg val loss={avg_val_loss:.4f}, "
            f"best val loss={best_val_loss:.4f}, best epoch={best_epoch}, val R2={r2_val:.3f}"
        )
    else:
        print(
            f"{model_type} | {split_type} | device={device}: avg train loss={avg_train_loss:.4f}, avg val loss={avg_val_loss:.4f}, "
            f"best val loss={best_val_loss:.4f}, best epoch={best_epoch}, val R2={r2_val:.3f}, test R2={r2_test:.3f}"
        )
    return result


def tune_gnn(
    split_type: str,
    search_space: dict,
    seeds: list[int],
    epochs: int = 50,
    batch_size: int = BATCH_SIZE_DEFAULT,
    early_stopping_patience: int = EARLY_STOPPING_PATIENCE_DEFAULT,
    min_delta: float = MIN_DELTA_DEFAULT,
    log_mlflow: bool = False,
    prefer_cuda: bool = True,
):
    import itertools
    import pandas as pd

    keys = ['lr', 'weight_decay', 'pooling', 'gnn_hidden_dim', 'gnn_num_layers', 'gnn_dropout']
    combos = list(itertools.product(*(search_space[k] for k in keys)))

    tuning_rows = []
    for i, (lr, wd, pooling, hidden, layers, dropout) in enumerate(combos, start=1):
        print(
            f"[{split_type}] config {i}/{len(combos)} | lr={lr} wd={wd} pool={pooling} "
            f"hidden={hidden} layers={layers} dropout={dropout}"
        )
        per_seed = []
        for seed in seeds:
            res = train_and_score(
                model_type='GNN',
                split_type=split_type,
                epochs=epochs,
                lr=lr,
                batch_size=batch_size,
                seed=seed,
                log_mlflow=log_mlflow,
                replace_existing=False,
                evaluate_test=False,
                early_stopping_patience=early_stopping_patience,
                min_delta=min_delta,
                weight_decay=wd,
                pooling=pooling,
                gnn_hidden_dim=hidden,
                gnn_num_layers=layers,
                gnn_dropout=dropout,
                prefer_cuda=prefer_cuda,
                deterministic=False,
                use_amp=True,
                use_model_cache=True,
                force_retrain=False,
                cache_namespace='gnn_tuning',
            )
            per_seed.append(res)

        val_r2 = [r['r2_val'] for r in per_seed]
        val_loss = [r['best_val_loss'] for r in per_seed]
        tuning_rows.append({
            'model': 'GNN',
            'split': split_type,
            'lr': lr,
            'weight_decay': wd,
            'pooling': pooling,
            'gnn_hidden_dim': hidden,
            'gnn_num_layers': layers,
            'gnn_dropout': dropout,
            'seeds': ','.join(str(s) for s in seeds),
            'epochs_selection': epochs,
            'r2_val_mean': float(np.mean(val_r2)),
            'r2_val_std': float(np.std(val_r2)),
            'best_val_loss_mean': float(np.mean(val_loss)),
            'best_val_loss_std': float(np.std(val_loss)),
        })

    df_tuning = pd.DataFrame(tuning_rows).sort_values(
        ['r2_val_mean', 'best_val_loss_mean'], ascending=[False, True]
    ).reset_index(drop=True)
    return df_tuning

In [115]:
# MLP - random split (porównanie po walidacji)
train_and_score(model_type="MLP", split_type="random", log_mlflow=False, evaluate_test=False)

MLP | random | device=cuda: avg train loss=0.4257, avg val loss=0.4854, best val loss=0.4543, best epoch=61, val R2=0.737

{'model': 'MLP',
 'split': 'random',
 'seed': 42,
 'epochs': 100,
 'epochs_trained': 73,
 'best_epoch': 61,
 'lr': 0.0003,
 'batch_size': 64,
 'weight_decay': 1e-05,
 'pooling': 'mean',
 'gnn_hidden_dim': 128,
 'gnn_num_layers': 4,
 'gnn_dropout': 0.15,
 'avg_train_loss': 0.42569581716972965,
 'avg_val_loss': 0.48538488060644236,
 'best_val_loss': 0.45433297991752625,
 'r2_val': 0.736980676651001,
 'r2_test': None,
 'device': 'cuda',
 'amp_enabled': True,
 'from_cache': False,
 'cache_path': 'processed_data/model_cache/default_37352a75cf5257ec.pt'}

In [116]:
# MLP - scaffold split (porównanie po walidacji)
train_and_score(model_type="MLP", split_type="scaffold", log_mlflow=False, evaluate_test=False)

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

MLP | scaffold | device=cuda: avg train loss=0.7985, avg val loss=0.7768, best val loss=0.6543, best epoch=5, val R2=0.424

{'model': 'MLP',
 'split': 'scaffold',
 'seed': 42,
 'epochs': 100,
 'epochs_trained': 17,
 'best_epoch': 5,
 'lr': 0.0003,
 'batch_size': 64,
 'weight_decay': 1e-05,
 'pooling': 'mean',
 'gnn_hidden_dim': 128,
 'gnn_num_layers': 4,
 'gnn_dropout': 0.15,
 'avg_train_loss': 0.7984636863704776,
 'avg_val_loss': 0.7767915284633637,
 'best_val_loss': 0.6543190622329712,
 'r2_val': 0.4241939187049866,
 'r2_test': None,
 'device': 'cuda',
 'amp_enabled': True,
 'from_cache': False,
 'cache_path': 'processed_data/model_cache/default_1e675e4c71a847e4.pt'}

In [117]:
# GNN - uruchamiamy tylko 1 najlepsza konfiguracje na split
BEST_GNN_CONFIGS = {
    'scaffold': {
        'lr': 3e-4,
        'weight_decay': 1e-5,
        'pooling': 'mean',
        'gnn_hidden_dim': 192,
        'gnn_num_layers': 4,
        'gnn_dropout': 0.10,
    },
    'random': {
        'lr': 3e-4,
        'weight_decay': 1e-5,
        'pooling': 'mean',
        'gnn_hidden_dim': 192,
        'gnn_num_layers': 4,
        'gnn_dropout': 0.10,
    },
}

gnn_selected_results = {}
for split_type, cfg in BEST_GNN_CONFIGS.items():
    gnn_selected_results[split_type] = train_and_score(
        model_type='GNN',
        split_type=split_type,
        epochs=100,
        batch_size=64,
        seed=42,
        log_mlflow=False,
        evaluate_test=False,
        early_stopping_patience=12,
        min_delta=1e-4,
        prefer_cuda=True,
        **cfg,
    )

gnn_selected_results

[scaffold] config 1/64 | lr=0.0001 wd=1e-05 pool=mean hidden=128 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2827, avg val loss=0.8908, best val loss=0.8043, best epoch=38, val R2=0.357

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5111, avg val loss=0.9502, best val loss=0.8191, best epoch=16, val R2=0.379

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4010, avg val loss=0.9968, best val loss=0.7919, best epoch=26, val R2=0.395
[scaffold] config 2/64 | lr=0.0001 wd=1e-05 pool=mean hidden=128 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6916, avg val loss=1.0036, best val loss=0.8470, best epoch=20, val R2=0.330

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7994, avg val loss=1.0614, best val loss=0.8609, best epoch=17, val R2=0.284

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.8638, avg val loss=1.0513, best val loss=0.8446, best epoch=16, val R2=0.394
[scaffold] config 3/64 | lr=0.0001 wd=1e-05 pool=mean hidden=128 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3468, avg val loss=0.8287, best val loss=0.6659, best epoch=23, val R2=0.422

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3186, avg val loss=0.9304, best val loss=0.7887, best epoch=18, val R2=0.358

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3921, avg val loss=0.9432, best val loss=0.8487, best epoch=16, val R2=0.342
[scaffold] config 4/64 | lr=0.0001 wd=1e-05 pool=mean hidden=128 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5406, avg val loss=0.8471, best val loss=0.7747, best epoch=43, val R2=0.360

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5705, avg val loss=0.9848, best val loss=0.8904, best epoch=18, val R2=0.384

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5013, avg val loss=0.9522, best val loss=0.8550, best epoch=32, val R2=0.386
[scaffold] config 5/64 | lr=0.0001 wd=1e-05 pool=mean hidden=192 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0150, avg val loss=0.9076, best val loss=0.7361, best epoch=50, val R2=0.419

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0909, avg val loss=0.8796, best val loss=0.7762, best epoch=29, val R2=0.384

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1097, avg val loss=0.9961, best val loss=0.8776, best epoch=32, val R2=0.344
[scaffold] config 6/64 | lr=0.0001 wd=1e-05 pool=mean hidden=192 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3627, avg val loss=0.9651, best val loss=0.8183, best epoch=23, val R2=0.340

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4158, avg val loss=0.9803, best val loss=0.8611, best epoch=19, val R2=0.351

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3305, avg val loss=0.9045, best val loss=0.8303, best epoch=34, val R2=0.309
[scaffold] config 7/64 | lr=0.0001 wd=1e-05 pool=mean hidden=192 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1364, avg val loss=0.9061, best val loss=0.7891, best epoch=26, val R2=0.367

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0266, avg val loss=0.7913, best val loss=0.6771, best epoch=38, val R2=0.467

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0301, avg val loss=0.8679, best val loss=0.7605, best epoch=35, val R2=0.348
[scaffold] config 8/64 | lr=0.0001 wd=1e-05 pool=mean hidden=192 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2821, avg val loss=0.9901, best val loss=0.8843, best epoch=38, val R2=0.368

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4495, avg val loss=0.9130, best val loss=0.7894, best epoch=20, val R2=0.435

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2820, avg val loss=0.9258, best val loss=0.7981, best epoch=31, val R2=0.369
[scaffold] config 9/64 | lr=0.0001 wd=1e-05 pool=add hidden=128 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6907, avg val loss=1.2579, best val loss=1.0413, best epoch=25, val R2=0.245

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2625, avg val loss=1.0052, best val loss=0.8193, best epoch=45, val R2=0.378

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.8436, avg val loss=1.1095, best val loss=0.9607, best epoch=16, val R2=0.239
[scaffold] config 10/64 | lr=0.0001 wd=1e-05 pool=add hidden=128 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.0663, avg val loss=1.2836, best val loss=0.9797, best epoch=34, val R2=0.156

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=3.3512, avg val loss=1.0986, best val loss=0.8542, best epoch=27, val R2=0.317

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=3.3302, avg val loss=1.3477, best val loss=1.1006, best epoch=20, val R2=0.181
[scaffold] config 11/64 | lr=0.0001 wd=1e-05 pool=add hidden=128 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.4366, avg val loss=1.5282, best val loss=1.0514, best epoch=17, val R2=0.190

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6693, avg val loss=1.0535, best val loss=0.8999, best epoch=41, val R2=0.232

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7038, avg val loss=1.1717, best val loss=1.0066, best epoch=49, val R2=0.278
[scaffold] config 12/64 | lr=0.0001 wd=1e-05 pool=add hidden=128 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=3.4314, avg val loss=1.2927, best val loss=0.9463, best epoch=17, val R2=0.192

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2612, avg val loss=0.9684, best val loss=0.7808, best epoch=34, val R2=0.368

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=3.2964, avg val loss=1.4528, best val loss=1.0005, best epoch=9, val R2=0.179
[scaffold] config 13/64 | lr=0.0001 wd=1e-05 pool=add hidden=192 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6509, avg val loss=1.0962, best val loss=0.8882, best epoch=20, val R2=0.289

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6539, avg val loss=1.1983, best val loss=1.0031, best epoch=24, val R2=0.151

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.0281, avg val loss=1.2282, best val loss=0.9668, best epoch=17, val R2=0.342
[scaffold] config 14/64 | lr=0.0001 wd=1e-05 pool=add hidden=192 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.1220, avg val loss=1.2097, best val loss=0.9788, best epoch=22, val R2=0.254

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3434, avg val loss=1.2686, best val loss=0.9854, best epoch=13, val R2=0.290

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.5877, avg val loss=1.2482, best val loss=0.8983, best epoch=16, val R2=0.236
[scaffold] config 15/64 | lr=0.0001 wd=1e-05 pool=add hidden=192 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2492, avg val loss=1.1166, best val loss=0.9136, best epoch=19, val R2=0.263

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5932, avg val loss=1.0908, best val loss=0.9638, best epoch=42, val R2=0.214

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2298, avg val loss=1.2618, best val loss=0.9572, best epoch=12, val R2=0.222
[scaffold] config 16/64 | lr=0.0001 wd=1e-05 pool=add hidden=192 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.6128, avg val loss=0.9308, best val loss=0.7973, best epoch=31, val R2=0.411

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.1829, avg val loss=1.3306, best val loss=1.1017, best epoch=43, val R2=0.157

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.4899, avg val loss=1.1674, best val loss=0.9829, best epoch=25, val R2=0.106
[scaffold] config 17/64 | lr=0.0001 wd=0.0001 pool=mean hidden=128 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4234, avg val loss=0.9004, best val loss=0.7693, best epoch=22, val R2=0.384

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4803, avg val loss=0.9077, best val loss=0.7464, best epoch=18, val R2=0.418

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3812, avg val loss=0.9010, best val loss=0.7863, best epoch=31, val R2=0.347
[scaffold] config 18/64 | lr=0.0001 wd=0.0001 pool=mean hidden=128 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6384, avg val loss=0.9883, best val loss=0.8819, best epoch=25, val R2=0.375

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5718, avg val loss=1.0517, best val loss=0.9136, best epoch=33, val R2=0.299

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.8170, avg val loss=1.0912, best val loss=0.9171, best epoch=18, val R2=0.264
[scaffold] config 19/64 | lr=0.0001 wd=0.0001 pool=mean hidden=128 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3469, avg val loss=1.0260, best val loss=0.8973, best epoch=23, val R2=0.265

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2161, avg val loss=0.9181, best val loss=0.8057, best epoch=30, val R2=0.335

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1545, avg val loss=0.9122, best val loss=0.7858, best epoch=43, val R2=0.391
[scaffold] config 20/64 | lr=0.0001 wd=0.0001 pool=mean hidden=128 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.8165, avg val loss=1.0496, best val loss=0.9042, best epoch=15, val R2=0.354

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4372, avg val loss=1.0338, best val loss=0.8746, best epoch=31, val R2=0.299

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5815, avg val loss=0.9969, best val loss=0.8779, best epoch=21, val R2=0.335
[scaffold] config 21/64 | lr=0.0001 wd=0.0001 pool=mean hidden=192 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2302, avg val loss=0.9489, best val loss=0.8245, best epoch=16, val R2=0.337

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1685, avg val loss=0.8503, best val loss=0.7589, best epoch=23, val R2=0.340

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1040, avg val loss=0.9161, best val loss=0.7600, best epoch=32, val R2=0.360
[scaffold] config 22/64 | lr=0.0001 wd=0.0001 pool=mean hidden=192 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3865, avg val loss=0.8568, best val loss=0.7222, best epoch=21, val R2=0.380

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3537, avg val loss=0.8914, best val loss=0.8023, best epoch=24, val R2=0.434

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2577, avg val loss=0.8773, best val loss=0.7679, best epoch=40, val R2=0.319
[scaffold] config 23/64 | lr=0.0001 wd=0.0001 pool=mean hidden=192 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0390, avg val loss=0.9378, best val loss=0.8238, best epoch=48, val R2=0.383

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2929, avg val loss=0.8953, best val loss=0.7236, best epoch=13, val R2=0.411

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2088, avg val loss=0.8977, best val loss=0.8072, best epoch=14, val R2=0.362
[scaffold] config 24/64 | lr=0.0001 wd=0.0001 pool=mean hidden=192 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2786, avg val loss=0.8756, best val loss=0.7661, best epoch=42, val R2=0.408

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2940, avg val loss=0.8406, best val loss=0.7409, best epoch=49, val R2=0.452

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3619, avg val loss=0.8956, best val loss=0.8038, best epoch=22, val R2=0.371
[scaffold] config 25/64 | lr=0.0001 wd=0.0001 pool=add hidden=128 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9452, avg val loss=1.2587, best val loss=0.9052, best epoch=12, val R2=0.217

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3947, avg val loss=1.0242, best val loss=0.8621, best epoch=35, val R2=0.332

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=3.2709, avg val loss=1.1852, best val loss=0.8686, best epoch=10, val R2=0.240
[scaffold] config 26/64 | lr=0.0001 wd=0.0001 pool=add hidden=128 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.4727, avg val loss=1.4710, best val loss=1.2076, best epoch=15, val R2=0.095

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=4.3335, avg val loss=1.3059, best val loss=1.0116, best epoch=14, val R2=0.248

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.8557, avg val loss=1.1517, best val loss=1.0376, best epoch=30, val R2=0.127
[scaffold] config 27/64 | lr=0.0001 wd=0.0001 pool=add hidden=128 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9010, avg val loss=1.2619, best val loss=0.9546, best epoch=41, val R2=0.173

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7657, avg val loss=1.0703, best val loss=0.8349, best epoch=29, val R2=0.339

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.8174, avg val loss=1.1295, best val loss=0.8840, best epoch=30, val R2=0.326
[scaffold] config 28/64 | lr=0.0001 wd=0.0001 pool=add hidden=128 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.6299, avg val loss=1.3207, best val loss=0.9915, best epoch=43, val R2=0.273

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2242, avg val loss=1.0048, best val loss=0.8906, best epoch=43, val R2=0.336

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.4505, avg val loss=1.1076, best val loss=0.8400, best epoch=32, val R2=0.285
[scaffold] config 29/64 | lr=0.0001 wd=0.0001 pool=add hidden=192 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4440, avg val loss=0.9476, best val loss=0.7352, best epoch=42, val R2=0.335

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6475, avg val loss=1.0450, best val loss=0.8389, best epoch=21, val R2=0.293

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3630, avg val loss=1.1668, best val loss=0.9382, best epoch=11, val R2=0.351
[scaffold] config 30/64 | lr=0.0001 wd=0.0001 pool=add hidden=192 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3531, avg val loss=1.2999, best val loss=0.9987, best epoch=13, val R2=0.174

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.5013, avg val loss=1.2824, best val loss=0.9434, best epoch=11, val R2=0.305

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.6217, avg val loss=0.9356, best val loss=0.7559, best epoch=17, val R2=0.420
[scaffold] config 31/64 | lr=0.0001 wd=0.0001 pool=add hidden=192 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7932, avg val loss=1.1574, best val loss=0.9608, best epoch=37, val R2=0.301

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7356, avg val loss=1.1165, best val loss=0.9106, best epoch=29, val R2=0.285

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.8628, avg val loss=1.1316, best val loss=0.9236, best epoch=25, val R2=0.217
[scaffold] config 32/64 | lr=0.0001 wd=0.0001 pool=add hidden=192 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2851, avg val loss=1.2292, best val loss=1.0130, best epoch=45, val R2=0.235

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.5902, avg val loss=1.0525, best val loss=0.9153, best epoch=21, val R2=0.253

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3297, avg val loss=1.0676, best val loss=0.8248, best epoch=29, val R2=0.362
[scaffold] config 33/64 | lr=0.0003 wd=1e-05 pool=mean hidden=128 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0616, avg val loss=0.9262, best val loss=0.7420, best epoch=38, val R2=0.387

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0990, avg val loss=0.9660, best val loss=0.7824, best epoch=33, val R2=0.454

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1674, avg val loss=1.0897, best val loss=0.8443, best epoch=30, val R2=0.374
[scaffold] config 34/64 | lr=0.0003 wd=1e-05 pool=mean hidden=128 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3348, avg val loss=1.0343, best val loss=0.8808, best epoch=33, val R2=0.355

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3981, avg val loss=1.0161, best val loss=0.8683, best epoch=27, val R2=0.342

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5751, avg val loss=0.9570, best val loss=0.8040, best epoch=15, val R2=0.371
[scaffold] config 35/64 | lr=0.0003 wd=1e-05 pool=mean hidden=128 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1996, avg val loss=0.9952, best val loss=0.7776, best epoch=23, val R2=0.366

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2824, avg val loss=1.3328, best val loss=0.8113, best epoch=9, val R2=0.327

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0626, avg val loss=0.9904, best val loss=0.7551, best epoch=32, val R2=0.432
[scaffold] config 36/64 | lr=0.0003 wd=1e-05 pool=mean hidden=128 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3633, avg val loss=0.9160, best val loss=0.7959, best epoch=46, val R2=0.357

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2762, avg val loss=0.9558, best val loss=0.7736, best epoch=40, val R2=0.407

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4511, avg val loss=1.0255, best val loss=0.8175, best epoch=16, val R2=0.404
[scaffold] config 37/64 | lr=0.0003 wd=1e-05 pool=mean hidden=192 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1135, avg val loss=1.2383, best val loss=0.7933, best epoch=18, val R2=0.391

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=0.9583, avg val loss=0.9384, best val loss=0.7266, best epoch=39, val R2=0.423

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=0.9695, avg val loss=0.8368, best val loss=0.6748, best epoch=41, val R2=0.423
[scaffold] config 38/64 | lr=0.0003 wd=1e-05 pool=mean hidden=192 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1769, avg val loss=1.0737, best val loss=0.8849, best epoch=32, val R2=0.388

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2480, avg val loss=0.9432, best val loss=0.7639, best epoch=24, val R2=0.424

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2610, avg val loss=1.0142, best val loss=0.8027, best epoch=24, val R2=0.405
[scaffold] config 39/64 | lr=0.0003 wd=1e-05 pool=mean hidden=192 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1197, avg val loss=0.9753, best val loss=0.7644, best epoch=19, val R2=0.372

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0327, avg val loss=1.0070, best val loss=0.8097, best epoch=29, val R2=0.305

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0692, avg val loss=0.9847, best val loss=0.6944, best epoch=20, val R2=0.444
[scaffold] config 40/64 | lr=0.0003 wd=1e-05 pool=mean hidden=192 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2417, avg val loss=1.0775, best val loss=0.8537, best epoch=28, val R2=0.361

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2562, avg val loss=0.9949, best val loss=0.8023, best epoch=32, val R2=0.378

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2073, avg val loss=0.8865, best val loss=0.6939, best epoch=34, val R2=0.464
[scaffold] config 41/64 | lr=0.0003 wd=1e-05 pool=add hidden=128 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5668, avg val loss=1.0601, best val loss=0.8172, best epoch=29, val R2=0.394

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2019, avg val loss=1.1829, best val loss=0.8962, best epoch=34, val R2=0.295

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9210, avg val loss=0.9274, best val loss=0.7877, best epoch=39, val R2=0.298
[scaffold] config 42/64 | lr=0.0003 wd=1e-05 pool=add hidden=128 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2100, avg val loss=1.5136, best val loss=1.0678, best epoch=18, val R2=0.184

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=4.3995, avg val loss=1.2457, best val loss=0.7873, best epoch=8, val R2=0.389

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3178, avg val loss=1.0813, best val loss=0.8082, best epoch=46, val R2=0.381
[scaffold] config 43/64 | lr=0.0003 wd=1e-05 pool=add hidden=128 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.0472, avg val loss=1.3080, best val loss=0.7965, best epoch=26, val R2=0.393

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.1749, avg val loss=1.3941, best val loss=1.0001, best epoch=7, val R2=0.289

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5884, avg val loss=1.1466, best val loss=0.8606, best epoch=36, val R2=0.288
[scaffold] config 44/64 | lr=0.0003 wd=1e-05 pool=add hidden=128 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3895, avg val loss=1.2955, best val loss=0.9343, best epoch=31, val R2=0.278

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9843, avg val loss=1.1908, best val loss=0.9306, best epoch=41, val R2=0.321

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3082, avg val loss=1.1534, best val loss=0.9071, best epoch=22, val R2=0.250
[scaffold] config 45/64 | lr=0.0003 wd=1e-05 pool=add hidden=192 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4718, avg val loss=1.1684, best val loss=0.8921, best epoch=49, val R2=0.326

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5354, avg val loss=1.1840, best val loss=0.8650, best epoch=37, val R2=0.381

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7017, avg val loss=1.2265, best val loss=0.8966, best epoch=31, val R2=0.323
[scaffold] config 46/64 | lr=0.0003 wd=1e-05 pool=add hidden=192 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7462, avg val loss=1.1001, best val loss=0.8395, best epoch=46, val R2=0.252

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.8812, avg val loss=1.0424, best val loss=0.8058, best epoch=35, val R2=0.377

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2162, avg val loss=1.1673, best val loss=0.9414, best epoch=29, val R2=0.308
[scaffold] config 47/64 | lr=0.0003 wd=1e-05 pool=add hidden=192 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.2995, avg val loss=1.5308, best val loss=0.9477, best epoch=17, val R2=0.289

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7256, avg val loss=1.1981, best val loss=0.9267, best epoch=40, val R2=0.343

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7422, avg val loss=1.0493, best val loss=0.8551, best epoch=32, val R2=0.309
[scaffold] config 48/64 | lr=0.0003 wd=1e-05 pool=add hidden=192 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.4339, avg val loss=1.1297, best val loss=0.8378, best epoch=28, val R2=0.344

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.0822, avg val loss=0.9962, best val loss=0.8171, best epoch=39, val R2=0.302

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.0787, avg val loss=1.2471, best val loss=0.8247, best epoch=35, val R2=0.381
[scaffold] config 49/64 | lr=0.0003 wd=0.0001 pool=mean hidden=128 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1920, avg val loss=1.0204, best val loss=0.7476, best epoch=21, val R2=0.343

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2171, avg val loss=1.0645, best val loss=0.8231, best epoch=22, val R2=0.350

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1087, avg val loss=0.9322, best val loss=0.8008, best epoch=36, val R2=0.394
[scaffold] config 50/64 | lr=0.0003 wd=0.0001 pool=mean hidden=128 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4362, avg val loss=0.9270, best val loss=0.8272, best epoch=25, val R2=0.296

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3639, avg val loss=1.0201, best val loss=0.8413, best epoch=35, val R2=0.345

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3655, avg val loss=0.9067, best val loss=0.7534, best epoch=35, val R2=0.398
[scaffold] config 51/64 | lr=0.0003 wd=0.0001 pool=mean hidden=128 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0814, avg val loss=1.0236, best val loss=0.8427, best epoch=42, val R2=0.358

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0229, avg val loss=0.9491, best val loss=0.8026, best epoch=37, val R2=0.336

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2570, avg val loss=0.9919, best val loss=0.7427, best epoch=11, val R2=0.339
[scaffold] config 52/64 | lr=0.0003 wd=0.0001 pool=mean hidden=128 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4877, avg val loss=0.9703, best val loss=0.8138, best epoch=26, val R2=0.447

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3165, avg val loss=0.8903, best val loss=0.7524, best epoch=32, val R2=0.401

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3506, avg val loss=0.9548, best val loss=0.8409, best epoch=32, val R2=0.290
[scaffold] config 53/64 | lr=0.0003 wd=0.0001 pool=mean hidden=192 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0376, avg val loss=0.9965, best val loss=0.7111, best epoch=27, val R2=0.386

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=0.9486, avg val loss=0.8894, best val loss=0.7269, best epoch=48, val R2=0.391

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=0.9682, avg val loss=0.8905, best val loss=0.7239, best epoch=47, val R2=0.428
[scaffold] config 54/64 | lr=0.0003 wd=0.0001 pool=mean hidden=192 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2340, avg val loss=0.9922, best val loss=0.7924, best epoch=25, val R2=0.389

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2517, avg val loss=0.9837, best val loss=0.7558, best epoch=25, val R2=0.397

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2034, avg val loss=0.9182, best val loss=0.7975, best epoch=34, val R2=0.396
[scaffold] config 55/64 | lr=0.0003 wd=0.0001 pool=mean hidden=192 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=0.9713, avg val loss=0.9584, best val loss=0.7926, best epoch=47, val R2=0.364

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.0558, avg val loss=0.8746, best val loss=0.6863, best epoch=26, val R2=0.413

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1098, avg val loss=1.0096, best val loss=0.7520, best epoch=18, val R2=0.393
[scaffold] config 56/64 | lr=0.0003 wd=0.0001 pool=mean hidden=192 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.2380, avg val loss=0.9862, best val loss=0.7887, best epoch=28, val R2=0.331

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.3053, avg val loss=1.0511, best val loss=0.7313, best epoch=25, val R2=0.432

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.1477, avg val loss=0.9436, best val loss=0.7485, best epoch=40, val R2=0.368
[scaffold] config 57/64 | lr=0.0003 wd=0.0001 pool=add hidden=128 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.4439, avg val loss=1.1337, best val loss=0.8212, best epoch=47, val R2=0.369

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.0809, avg val loss=1.0899, best val loss=0.8394, best epoch=39, val R2=0.360

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.0262, avg val loss=1.1080, best val loss=0.8781, best epoch=30, val R2=0.300
[scaffold] config 58/64 | lr=0.0003 wd=0.0001 pool=add hidden=128 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.1435, avg val loss=1.4268, best val loss=1.0908, best epoch=20, val R2=0.197

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.7822, avg val loss=1.1295, best val loss=0.8278, best epoch=31, val R2=0.431

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3884, avg val loss=1.1431, best val loss=0.9228, best epoch=48, val R2=0.209
[scaffold] config 59/64 | lr=0.0003 wd=0.0001 pool=add hidden=128 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.0545, avg val loss=1.1364, best val loss=0.7511, best epoch=21, val R2=0.359

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5549, avg val loss=1.1249, best val loss=0.8856, best epoch=37, val R2=0.246

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.8963, avg val loss=1.2044, best val loss=0.9052, best epoch=16, val R2=0.310
[scaffold] config 60/64 | lr=0.0003 wd=0.0001 pool=add hidden=128 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.1526, avg val loss=1.0925, best val loss=0.7232, best epoch=40, val R2=0.411

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9928, avg val loss=1.0741, best val loss=0.7990, best epoch=35, val R2=0.370

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=3.0061, avg val loss=1.3503, best val loss=1.0114, best epoch=7, val R2=0.265
[scaffold] config 61/64 | lr=0.0003 wd=0.0001 pool=add hidden=192 layers=4 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.5274, avg val loss=1.2334, best val loss=0.8925, best epoch=30, val R2=0.211

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9442, avg val loss=1.1600, best val loss=0.8956, best epoch=9, val R2=0.339

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6148, avg val loss=1.2307, best val loss=0.8666, best epoch=47, val R2=0.359
[scaffold] config 62/64 | lr=0.0003 wd=0.0001 pool=add hidden=192 layers=4 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.8229, avg val loss=1.2603, best val loss=0.9672, best epoch=35, val R2=0.205

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9823, avg val loss=1.2817, best val loss=0.9436, best epoch=28, val R2=0.327

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9322, avg val loss=1.1854, best val loss=0.8769, best epoch=47, val R2=0.309
[scaffold] config 63/64 | lr=0.0003 wd=0.0001 pool=add hidden=192 layers=5 dropout=0.1

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.7114, avg val loss=1.1305, best val loss=0.8193, best epoch=40, val R2=0.325

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.9748, avg val loss=1.3344, best val loss=1.0180, best epoch=23, val R2=0.124

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=1.6531, avg val loss=1.3194, best val loss=1.0642, best epoch=49, val R2=0.104
[scaffold] config 64/64 | lr=0.0003 wd=0.0001 pool=add hidden=192 layers=5 dropout=0.2

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.4965, avg val loss=1.0743, best val loss=0.7691, best epoch=25, val R2=0.275

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.5787, avg val loss=1.5201, best val loss=0.9514, best epoch=14, val R2=0.171

/tmp/ipykernel_11445/3019257381.py:13: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  df_scaff = df_fp.with_row_count('row_id').with_columns(

GNN | scaffold | device=cuda: avg train loss=2.3704, avg val loss=1.2229, best val loss=0.8562, best epoch=26, val R2=0.366

,model,split,lr,weight_decay,pooling,gnn_hidden_dim,gnn_num_layers,gnn_dropout,seeds,epochs_selection,r2_val_mean,r2_val_std,best_val_loss_mean,best_val_loss_std
0,GNN,scaffold,0.0003,0.00001,mean,192,4,0.1,"42,1337,2025",50,0.412290,0.015276,0.731562,0.048484
1,GNN,scaffold,0.0001,0.00010,mean,192,5,0.2,"42,1337,2025",50,0.410373,0.032820,0.770268,0.025847
2,GNN,scaffold,0.0003,0.00001,mean,192,4,0.2,"42,1337,2025",50,0.405325,0.014721,0.817164,0.050428
3,GNN,scaffold,0.0003,0.00001,mean,128,4,0.1,"42,1337,2025",50,0.405284,0.035204,0.789574,0.042082
4,GNN,scaffold,0.0003,0.00010,mean,192,4,0.1,"42,1337,2025",50,0.401900,0.018907,0.720669,0.006856
5,GNN,scaffold,0.0003,0.00001,mean,192,5,0.2,"42,1337,2025",50,0.401286,0.045205,0.783307,0.066584
6,GNN,scaffold,0.0003,0.00010,mean,192,4,0.2,"42,1337,2025",50,0.394161,0.003765,0.781896,0.018589
7,GNN,scaffold,0.0001,0.00001,mean,192,5,0.1,"42,1337,2025",50,0.394116,0.052207,0.742242,0.047505
8,GNN,scaffold,0.0001,0.00001,mean,192,5,0.2,"42,1337,2025",50,0.390566,0.031182,0.823917,0.042860
9,GNN,scaffold,0.0003,0.00010,mean,192,5,0.1,"42,1337,2025",50,0.390327,0.020043,0.743632,0.043763

In [118]:
# Podsumowanie wybranych konfiguracji GNN
import pandas as pd

if 'gnn_selected_results' in globals() and gnn_selected_results:
    cfg_df = pd.DataFrame([
        {'split': split, **cfg}
        for split, cfg in BEST_GNN_CONFIGS.items()
    ])
    score_df = pd.DataFrame([
        {'split': split, 'r2_val': res['r2_val'], 'best_val_loss': res['best_val_loss']}
        for split, res in gnn_selected_results.items()
    ])
    display(cfg_df.merge(score_df, on='split', how='left'))
else:
    print('Uruchom najpierw komorke z BEST_GNN_CONFIGS.')

,model,split,lr,weight_decay,pooling,gnn_hidden_dim,gnn_num_layers,gnn_dropout,seeds,epochs_selection,r2_val_mean,r2_val_std,best_val_loss_mean,best_val_loss_std
0,GNN,scaffold,0.0003,0.00001,mean,192,4,0.1,"42,1337,2025",50,0.412290,0.015276,0.731562,0.048484
1,GNN,scaffold,0.0001,0.00010,mean,192,5,0.2,"42,1337,2025",50,0.410373,0.032820,0.770268,0.025847
2,GNN,scaffold,0.0003,0.00001,mean,192,4,0.2,"42,1337,2025",50,0.405325,0.014721,0.817164,0.050428
3,GNN,scaffold,0.0003,0.00001,mean,128,4,0.1,"42,1337,2025",50,0.405284,0.035204,0.789574,0.042082
4,GNN,scaffold,0.0003,0.00010,mean,192,4,0.1,"42,1337,2025",50,0.401900,0.018907,0.720669,0.006856
5,GNN,scaffold,0.0003,0.00001,mean,192,5,0.2,"42,1337,2025",50,0.401286,0.045205,0.783307,0.066584
6,GNN,scaffold,0.0003,0.00010,mean,192,4,0.2,"42,1337,2025",50,0.394161,0.003765,0.781896,0.018589
7,GNN,scaffold,0.0001,0.00001,mean,192,5,0.1,"42,1337,2025",50,0.394116,0.052207,0.742242,0.047505
8,GNN,scaffold,0.0001,0.00001,mean,192,5,0.2,"42,1337,2025",50,0.390566,0.031182,0.823917,0.042860
9,GNN,scaffold,0.0003,0.00010,mean,192,5,0.1,"42,1337,2025",50,0.390327,0.020043,0.743632,0.043763
10,GNN,scaffold,0.0003,0.00001,mean,128,5,0.2,"42,1337,2025",50,0.389262,0.022824,0.795673,0.017896
11,GNN,scaffold,0.0001,0.00010,mean,192,5,0.1,"42,1337,2025",50,0.385367,0.019879,0.784885,0.043873
12,GNN,scaffold,0.0001,0.00010,mean,128,4,0.1,"42,1337,2025",50,0.383216,0.029011,0.767347,0.016363
13,GNN,scaffold,0.0001,0.00001,mean,192,4,0.1,"42,1337,2025",50,0.382557,0.030753,0.796637,0.059527
14,GNN,scaffold,0.0003,0.00010,mean,128,5,0.2,"42,1337,2025",50,0.379145,0.065690,0.802387,0.037017
15,GNN,scaffold,0.0001,0.00010,mean,192,4,0.2,"42,1337,2025",50,0.377714,0.046964,0.764137,0.032819
16,GNN,scaffold,0.0001,0.00001,mean,128,4,0.1,"42,1337,2025",50,0.377212,0.015729,0.805099,0.011138
17,GNN,scaffold,0.0003,0.00010,mean,192,5,0.2,"42,1337,2025",50,0.376648,0.041706,0.756179,0.024046
18,GNN,scaffold,0.0001,0.00001,mean,128,5,0.2,"42,1337,2025",50,0.376529,0.011734,0.840047,0.048421
19,GNN,scaffold,0.0003,0.00001,mean,128,5,0.1,"42,1337,2025",50,0.375173,0.043255,0.781339,0.023063

In [119]:
# Zestawienie wynikow w tabeli
import pandas as pd

if not results_table:
    print('Brak zebranych wynikow. Uruchom najpierw komorki treningowe.')
else:
    df_results = pd.DataFrame(results_table)
    preferred_cols = [
        'model',
        'split',
        'seed',
        'epochs',
        'epochs_trained',
        'best_epoch',
        'lr',
        'batch_size',
        'weight_decay',
        'pooling',
        'gnn_hidden_dim',
        'gnn_num_layers',
        'gnn_dropout',
        'avg_train_loss',
        'avg_val_loss',
        'best_val_loss',
        'r2_val',
        'r2_test',
        'from_cache',
        'cache_path',
    ]
    cols_to_show = [c for c in preferred_cols if c in df_results.columns]
    display(df_results[cols_to_show].sort_values(['r2_val'], ascending=False).reset_index(drop=True))

,model,split,seed,epochs,epochs_trained,best_epoch,lr,batch_size,weight_decay,pooling,gnn_hidden_dim,gnn_num_layers,gnn_dropout,avg_train_loss,avg_val_loss,best_val_loss,r2_val,r2_test,from_cache,cache_path
0,MLP,random,42,100,73,61,0.0003,64,0.00001,mean,128,4,0.15,0.425696,0.485385,0.454333,0.736981,None,False,processed_data/model_cache/default_37352a75cf5...
1,GNN,scaffold,1337,50,48,38,0.0001,64,0.00001,mean,192,5,0.10,1.026591,0.791252,0.677122,0.467200,None,False,processed_data/model_cache/gnn_tuning_7c2b220c...
2,GNN,scaffold,2025,50,44,34,0.0003,64,0.00001,mean,192,5,0.20,1.207298,0.886537,0.693939,0.464469,None,False,processed_data/model_cache/gnn_tuning_681ef33d...
3,GNN,scaffold,1337,50,43,33,0.0003,64,0.00001,mean,128,4,0.10,1.098997,0.966005,0.782356,0.454480,None,False,processed_data/model_cache/gnn_tuning_30eaa516...
4,GNN,scaffold,1337,50,50,49,0.0001,64,0.00010,mean,192,5,0.20,1.294009,0.840580,0.740912,0.451513,None,False,processed_data/model_cache/gnn_tuning_0c0bc2ee...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,GNN,scaffold,2025,50,40,30,0.0001,64,0.00010,add,128,4,0.20,2.855722,1.151659,1.037644,0.126728,None,False,processed_data/model_cache/gnn_tuning_4150af63...
190,GNN,scaffold,1337,50,33,23,0.0003,64,0.00010,add,192,5,0.10,1.974791,1.334378,1.018025,0.123542,None,False,processed_data/model_cache/gnn_tuning_2c8a2c06...
191,GNN,scaffold,2025,50,35,25,0.0001,64,0.00001,add,192,5,0.20,2.489868,1.167408,0.982883,0.105558,None,False,processed_data/model_cache/gnn_tuning_6271422f...
192,GNN,scaffold,2025,50,50,49,0.0003,64,0.00010,add,192,5,0.10,1.653086,1.319363,1.064170,0.104295,None,False,processed_data/model_cache/gnn_tuning_99e572fa...
193,GNN,scaffold,42,50,25,15,0.0001,64,0.00010,add,128,4,0.20,2.472682,1.470952,1.207634,0.094714,None,False,processed_data/model_cache/gnn_tuning_19218a03...

In [120]:
# Finalny test uruchom raz dla najlepszego wariantu wybranego po walidacji.
# Przyklad: pobierz top konfiguracje i odpal dluzszy trening na 1 seed z testem.
# best_cfg = gnn_scaffold_tuning.iloc[0].to_dict()
# final_result = train_and_score(
#     model_type='GNN',
#     split_type='scaffold',
#     epochs=100,
#     lr=best_cfg['lr'],
#     batch_size=64,
#     seed=42,
#     weight_decay=best_cfg['weight_decay'],
#     pooling=best_cfg['pooling'],
#     gnn_hidden_dim=int(best_cfg['gnn_hidden_dim']),
#     gnn_num_layers=int(best_cfg['gnn_num_layers']),
#     gnn_dropout=best_cfg['gnn_dropout'],
#     log_mlflow=True,
#     evaluate_test=True,
#     replace_existing=False,
#     prefer_cuda=True,
#     deterministic=False,
#     use_amp=True,
# )

# Wnioski z porownania modeli

- Ranking wariantow wykonuj na podstawie **R2 walidacyjnego**, a zbior testowy uruchamiaj tylko raz dla finalisty.
- Dla GNN raportuj srednia i odchylenie standardowe po wielu seedach (minimum 3).
- Scaffold split traktuj jako glowny test uogolniania chemicznego na nowe rusztowania.
- Najpierw wybierz najlepsza konfiguracje po `gnn_scaffold_tuning`, dopiero potem uruchom finalny test.